### ISSUE TITLE
[bug] using a property in a child attr {} binding uses the parent property if named the same as child

### ISSUE THREAD

**Issue by Anima-t3d** [ManuelDeLeon/viewmodel#117] opened 2015-10-08 06:35 UTC
When you are using parent-child templates and you use the `data-bind='attr: { name: value }'` if value is retrieved from a property in the child which has the same name as the property name in the parent it uses the parent property to retrieve the value.

## HTML
```html
<template name="_BreadCrumb">
	<div class="ui breadcrumb">
		<a class="section" href="/">OK</a>
		{{#each parts}}
			{{> _BreadCrumbPart }}
		{{/each}}
	</div>
	<div class="ui breadcrumb">
		<a class="section" href="/">Bugged</a>
		{{#each parts}}
			{{> _BreadCrumbPartBugged }}
		{{/each}}
	</div>
</template>

<template name="_BreadCrumbPart">
	|
	<a class="section" data-bind='attr: { href: url2 }'>{{ name }}</a>
</template>

<template name="_BreadCrumbPartBugged">
	|
	<a class="section" data-bind='attr: { href: url }'>{{ name }}</a>
</template>
```
## JS
```javascript
Template._BreadCrumb.viewmodel(
	{
		parts: function () {
			var parts = [
				{
					url: 'parentUrl',
					name: 'parentName',
					last: false
				},
				{
					url: 'parentUrl',
					name: 'parentName',
					last: true
				}
			];
			return parts;
		}
	}, ['parts']
);

Template._BreadCrumbPart.viewmodel(
	function (part) {
		return {
			url2: function () {
				return part.last === true ? 'child' : part.url;
			}
		};
	}
);

Template._BreadCrumbPartBugged.viewmodel(
	function (part) {
		return {
			url: function () {
				return part.last === true ? 'child' : part.url;
			}
		};
	}
);

```
## Expected behavior
To return child on the last item, but it still shows parentName
## Workaround
Rename the property in either the parent or the child.

**Comment by ManuelDeLeon** [comment] 2015-10-08 08:38
There's  a reason why it does it, but I agree it shouldn't be that way.
I'll fix it.

**Comment by ManuelDeLeon** [comment] 2015-12-04 17:28
Sorry for the late reply. ViewModel version 2 has taken up all my time lately.

I thought I understood this one but now I'm running your example and I don't know what the problem is...

**Comment by Anima-t3d** [comment] 2015-12-07 01:40
In `BreadCrumbPartBugged` the url property value is taken from the parent and not from the item's actual VM (the child of the parent).

```html
<template name="_BreadCrumbPartBugged">
    |
    <a class="section" data-bind='attr: { href: url }'>{{ name }}</a>
</template>
```
In the code above `url` value will be retrieved from the parent's VM since that one also has a url property.

If the parent does not have a property with the same name as the child it will take the child's property correctly.

I hope it is more clear now? 
I think it might be related to: https://github.com/ManuelDeLeon/viewmodel/issues/123

**Comment by ManuelDeLeon** [comment] 2016-02-15 23:03
I'm sorry but I'm closing this one. I re-read it every week and it always gives me a headache. If this is still a problem please create a new issue with an idiot proof repro (removing absolutely everything that isn't required to show the problem).

**Closed by ManuelDeLeon** 2016-02-15 23:03 UTC

**Comment by Anima-t3d** [comment] 2016-02-16 05:00
Ok thanks for the info. I think it's more or less fixed in newer versions, besides there is v2 now. Just in case it might give you some new found knowledge. If parent VM has property url (value `"www.parent.com"`and child has property url (value `"www.child.org"`). If in child you `data-bind=" attr:{xx: url}"` it will take the url property value from the parent instead of the child. Expected is `www.child.org` but it actually takes `www.parent.com`
