### ISSUE TITLE
Exception from Tracker afterFlush function: p.vm[p.property] is not a function

### ISSUE THREAD

**Issue by elegos** [ManuelDeLeon/viewmodel#20] opened 2015-01-04 19:07 UTC
Hello!

I'd like to try this MVVM library instead of knockout hoping it will integrate better in meteor.

I'm currently trying to setup a simple template, but I'm getting that error when I create the viewmodel instance.

Here is the full stack:

    Exception from Tracker afterFlush function: p.vm[p.property] is not a function
    ViewModel</<@http://home.giacomofurlan.name/packages/manuel_viewmodel.js?92d06858ece30fbbd739a9b8a0d63783c4642e8a:210:45
    ViewModel/this.bind</</<@http://home.giacomofurlan.name/packages/manuel_viewmodel.js?92d06858ece30fbbd739a9b8a0d63783c4642e8a:633:27
    .each@http://home.giacomofurlan.name/packages/jquery.js?265926494aaa3929cd2e30da265211c5929f37a4:417:14
    jQuery.prototype.each@http://home.giacomofurlan.name/packages/jquery.js?265926494aaa3929cd2e30da265211c5929f37a4:170:10
    ViewModel/this.bind</<@http://home.giacomofurlan.name/packages/manuel_viewmodel.js?92d06858ece30fbbd739a9b8a0d63783c4642e8a:625:9
    Template.Wizard.rendered@http://home.giacomofurlan.name/client/templates/Wizard/Wizard.coffee.js?ffc973fc8a574723b7eb915f2183dca4befc51de:28:7
    Template.prototype.constructView/<@http://home.giacomofurlan.name/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:3008:7
    Blaze.View.prototype.onViewReady/fire/</<@http://home.giacomofurlan.name/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1733:11
    Blaze._withCurrentView@http://home.giacomofurlan.name/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:2043:12
    Blaze.View.prototype.onViewReady/fire/<@http://home.giacomofurlan.name/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1732:9
    Tracker.flush@http://home.giacomofurlan.name/packages/tracker.js?7f0c5481709a504dd2254ba2a71c1cee78adc280:448:11

This is the simple snippet I'm using to init the viewmodel:

	Template.Wizard.created = ->
	  tpl = @
	  @Iron = Iron
	  
	  @CharacterData = new ReactiveVar()
	  
	  @autorun ->
	    tpl.CharacterData.set tpl.Iron.controller().data()
	    return
	  
	  return

	Template.Wizard.rendered = ->
	  vm = null
	  
	  if @CharacterData.get()
	    data = @CharacterData.get()
	    if vm == null
	      vm = new ViewModel data
	      vm.bind @
	    else
	      vm.extend @CharacterData.get()

Data binding seems to work properly (at least the variables show correctly, I haven't looked at if they're updated, yet). Am I doing something wrong?

Thanks

EDIT: Additional details: the error occours only when I bind the property to the template with the following syntax:

    data-bind="value: General.Name"

EDIT2: It seems it's related to the sublevel. If I bind a one-level VALUE property (i.e. `data-bind="value: FirstLevelProperty"`), it runs correctly. If I bind a value with a sub-property, it will throw the error. If I bind the TEXT, it will work correctly. Not sure what's going on.

**Comment by ManuelDeLeon** [comment] 2015-01-04 20:34
That's a weird way of doing things. You don't need the autorun or the null
check or setting values in the template instance. Just create your
viewmodel in the Create event (using this.data if the parent template is
passing some values), and bind it in the rendered event. See the examples.

**Comment by elegos** [comment] 2015-01-04 20:43
If I don't use the autorun, how can I detect when the data passed from Iron Router has changed? i.e. from /path/id1 to /path/id2?

**Comment by ManuelDeLeon** [comment] 2015-01-04 21:09
When you switch the page a new template will be created with the new data
context.

**Comment by elegos** [comment] 2015-01-04 21:11
Please see the updated reply, isn't that the right way to bind things?

**Comment by ManuelDeLeon** [comment] 2015-01-04 21:58
What's the value of Iron.controller().data()?

**Comment by elegos** [comment] 2015-01-04 22:03
This is the JSON stringified version of the object:
`{"_id":"YWD3Bt5mnxZLB4B8S","Attributes":{"Mental":{"Intelligence":3,"Wits":3,"Resolve":2,"TotalSpent":5},"Physical":{"Strength":3,"Dexterity":2,"Stamina":2,"TotalSpent":4},"Social":{"Presence":2,"Manipulation":1,"Composure":3,"TotalSpent":3}},"CreatedBy":"NQCcrm3Z7cuperAu8","CreationDate":1420290345350,"Defense":2,"General":{"Name":"Jack Frost","Concept":"Fotografo reporter","Age":27,"Faction":"Fotografi dell'Altro Mondo","Virtue":"Speranza","Vice":"Lussuria","Size":5,"Morality":7},"Health":7,"Initiative":5,"LastUpdateDate":1420375975104,"LastUpdatedBy":"NQCcrm3Z7cuperAu8","Merits":[{"Description":"test","Min":1,"Max":1,"Value":1}],"SaveName":"Jack Frost","Skills":{"Mental":{"Academics":0,"Computer":0,"Crafts":0,"Investigation":0,"Medicine":0,"Occult":0,"Politics":0,"Science":0,"TotalSpent":0},"Physical":{"Athletics":0,"Brawl":0,"Drive":0,"Firearms":0,"Larceny":0,"Stealth":0,"Survival":0,"Weaponry":0,"TotalSpent":0},"Social":{"AnimalKen":0,"Empathy":0,"Expression":0,"Intimidation":0,"Persuasion":0,"Socialize":0,"Streetwise":0,"Subterfuge":0,"TotalSpent":0},"Specialities":[{"value":""},{"value":""},{"value":""},{"value":""}]},"Speed":10,"Willpower":5}`

**Comment by ManuelDeLeon** [comment] 2015-01-04 22:56
The problem is the structure of your context:
```
{
  General: {
    Name: "Something"
  }
}
```
ViewModel grabs this and it creates a property named "General" with the value:
```
{ Name: "Something" }
```
The value of "General" is an object so "Name" isn't a reactive value, it's just part of the object which "General" holds.

You can use General.Name in a read only manner:
```
<label data-bind="text: General.Name"></label>
```
But not to write:
```
<input data-bind="value: General.Name">
```
In your case just extract the name from the context:
```
new ViewModel
  name: Iron.controller().data().General.Name
```
If you need to bind to other properties of the context you can either add them manually like the name in the previous code, or add them in one shot and then extend the view model with the name:
```
new ViewModel(Iron.controller().data()).extend
  name: context.General.Name
```
And then bind to "name":
```
<input data-bind="value: name">
```

**Comment by elegos** [comment] 2015-01-04 23:27
Thank you Manuel.

As you can see the model is pretty much complicated. I for sure can rebuild the object during the saving process, but I hoped this library could help me doing this "for me". Also I thought about dividing the model in several parts (I've got subtemplates running in the page, so it could be not a problem), but I need to access some parts in order to calculate others.

So my next question is: is it possible to pass the subtemplates the partial viewmodel from the main template not by copy but by reference, so that I can keep trace of the changes and thus make the calculated variables reactive?

**Comment by ManuelDeLeon** [comment] 2015-01-04 23:56
Sorry but no, each vm will be independent of each other. I'll most likely add an "extendAll" method to make all sub-properties reactive. You don't want to wait for it though =/

**Comment by elegos** [comment] 2015-01-05 01:28
I once made an extension for knockout in order to update an existing model with fresh data - with any level of nesting. It had the downside that observableArrays rendered with the foreach statement were updated, but the contents rendered were duplicated somehow. I post it here, if this could help you make it :)

It is basically a recursive function: if the nth element is an object, call the function with the new subpath, otherwise if there is a function in the model with the same path, set it with the data, otherwise create a static variable in the model.

https://gist.github.com/elegos/8034f0f4935fdb510b72

**Comment by ManuelDeLeon** [comment] 2015-01-05 05:13
Thx. I'll close this for now (you probably know what you want to do).

**Closed by ManuelDeLeon** 2015-01-05 05:13 UTC
