### ISSUE TITLE
docs  - update array info

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#268] opened 2016-08-19 11:36 UTC
`reactive arrays` link is unreachable; suggest that it be changed to https://github.com/ManuelDeLeon/ReactiveArray

**Comment by fvpDev** [comment] 2016-08-19 15:40
Duplicate of #265

**Comment by ManuelDeLeon** [comment] 2016-08-19 19:19
Updated docs, will deploy later.

**Closed by ManuelDeLeon** 2016-08-19 19:19 UTC
