### ISSUE TITLE
Exception in template helper

### ISSUE THREAD

**Issue by hluz** [ManuelDeLeon/viewmodel#223] opened 2016-04-02 05:36 UTC
When displaying a template under a ```{{#each xxx}}``` helper, where xxx is an array of mongo subdocuments, under some sequence of events an exception is triggered:

```
Exception in template helper: TypeError: Cannot read property 'apply' of undefined
 at Object.helpers.(anonymous function) (http://localhost:3000/packages/manuel_viewmodel.js?hash=c6a7...
```

This is a weird one, and took me a while to reproduce it get a minimal repro... I can work around it, but knowing it is there triggers my OCD... and since I'm not sure it will not trip other issues, here it is. Detailed explanation of the sequence of actions that trigger this can be found as comments to the code in the repro: https://github.com/hluz/vmArr.git

**Comment by ManuelDeLeon** [comment] 2016-04-02 05:45
If this has something to do with the latest changes I'm going to lose it, I
really will...

I'll check it out tomorrow. Thanks for the help.

**Comment by hluz** [comment] 2016-04-02 05:49
No, don't stress. I don't think it has anything to do with bindings or event listeners...

and thank **you** for your package.

**Comment by fvpDev** [comment] 2016-04-02 12:13
#212; has been happening for me for a while, actually. I'm gonna check out this repro. Thanks for making one.

**Comment by ManuelDeLeon** [comment] 2016-04-02 17:25
Very nice repro.

It's clear that I have to return undefined to Blaze if the view model
doesn't have the property. Right now it assumes that if the first view
model has a property then the second one will too. That's not the case for
inherited properties.

I was thinking of giving out a message saying the inherited properties
changed but that will probably be more of a nuisance than anything.

I'll fix it soon.

**Comment by ManuelDeLeon** [comment] 2016-04-02 19:01
Fixed on v4.0.12

Note that you can still get into trouble if your view models are inheriting properties from objects which have different properties. You can still create a situation where the Blaze helper always returns undefined because the view model doesn't know about the properties by the time the helpers are set. I wouldn't be able to do anything about it.

If the objects you're inheriting properties from have different sets of properties then you should explicitly declare the properties in the view model. In this case you should add `items` to `showGroup` (even though it works without it).

**Closed by ManuelDeLeon** 2016-04-02 19:01 UTC

**Comment by ManuelDeLeon** [comment] 2016-04-02 19:31
Just to clarify, in the case of this repro the showGroup view model is inheriting from two objects with a different set of properties:

```js
Groups.insert({
    cd:"A",
    name:"name A"
});
Groups.insert({
  cd:"B",
    name: "name B",
    items: [{name: 'item1'}, {name: 'item2'}]
});
```
In this case B has `items` while A doesn't.

**Comment by hluz** [comment] 2016-04-02 23:49
Thanks for looking into this so quick. I should have described it as "tricky" rather than "weird"...  v4.0.12 fixes the exception but it now produces the wrong results (the same repro will do).

Select "B, and then "A" (without selecting "none", which has the effect of removing the ```showGroup``` template). In this case, when showing "A", the ```items``` helper does not get removed from the viewmodel and still returns ```[{name: 'item1'}, {name: 'item2'}]``` even though object "A" has no ```item``` property.

Interesting though, if template ```showGroup``` has no own properties defined (i.e., all are inherited) then it behaves properly (which may indicate that a fix may be possible).

I think this resulting behaviour is worst than before (which could be fixed by just adding a ```items``` property explicitly in the viewmodel as you mentioned).

**Comment by ManuelDeLeon** [comment] 2016-04-03 03:31
Believe it or not it's working as designed.

The problem is that you're taking 2 things which are problematic by themselves and putting them together. You're using `#with` and inheriting from a collection with different number/kinds of attributes. I don't recommend doing either of those and, as you can probably tell, I *really* don't recommend using them at the same time.

In your case when you select B, the view model inside the `#with` displays the items correctly. When you switch to A, the view model stays the same but it loads the properties from the new context (document A). Here's the problem, the view model already has `items` so when the context changes the view model loads the properties from the context (cd and name) and leaves `items` as it is.

**Comment by hluz** [comment] 2016-04-03 03:46
Ok. I have no unsurpassable problem in the real app (this repo is very contrived to isolate the issue). And thinking about how viewmodel does things it makes sense. Maybe some note on the docs to highlight this to unsuspecting users?

Thinking to myself here: what would be good (don't know if achievable) is a way to separate/identify between inherited properties and non-inherited (defined in the current viewmodel)... the way it stands we can probably have scenarios where a component viewmodel can inadvertently have a property overriden by a change made to the parent component viewmodel by adding a property with a same name that already exited in the child component...

**Comment by ManuelDeLeon** [comment] 2016-04-03 03:51
I thought of that but it sets of a bunch of alarms in my brain. I may warm
up to the idea later.

**Comment by fvpDev** [comment] 2016-04-03 13:48
Has there ever been a scenario in programming where inherited and non-inherited props have had to be separated?

**Comment by ManuelDeLeon** [comment] 2016-04-03 13:54
All the time for me. Like a view model for a template that is inside an
each block, and I want to define more UI related properties.

**Comment by fvpDev** [comment] 2016-04-03 13:56
I guess it's just too early for me to wrap my head around it right now lol
